{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-23414] Issue with network connection", "trace": "('/Users/olehlazeba/PycharmProjects/pytest_2023/tests/users/test_users.py', 24, 'Skipped: [ISSUE-23414] Issue with network connection')"}, "description": "\n    In that we try to check that 1 is equal 1\n    :return:\n    ", "start": 1708779759462, "stop": 1708779759462, "uuid": "2b05a216-7b5c-4542-aa5e-f025835e4754", "historyId": "ecdad97ca3d7a3be9fe1de0e65fa7b4f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-23414] Issue with network connection')"}, {"name": "tag", "value": "production"}, {"name": "tag", "value": "development"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "cee4655380e4"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}