{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-23414] Issue with network connection", "trace": "('/home/fisher/PycharmProjects/pytest_2023/tests/users/test_users.py', 24, 'Skipped: [ISSUE-23414] Issue with network connection')"}, "description": "\n    In that we try to check that 1 is equal 1\n    :return:\n    ", "start": 1710326592405, "stop": 1710326592405, "uuid": "70e506c9-143c-42c6-92a5-61e69e4967c3", "historyId": "ecdad97ca3d7a3be9fe1de0e65fa7b4f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-23414] Issue with network connection')"}, {"name": "tag", "value": "production"}, {"name": "tag", "value": "development"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "0ce513a6f4a3"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}